export const TOP_SIZES = [
    'XS',
    'S',
    'M',
    'L',
    'XL',
    'XXL+',
    'spaceSeperator',
    '0',
    '2',
    '4',
    '6',
    '8',
    '10',
    '12',
    '14',
    '16',
    '18',
    '22',
    '24+'
];

export const DRESS_SIZES = ['0', '2', '4', '6', '8', '10', '12', '14', '16', '18', '22', '24+'];

export const BOTTOM_SIZES = ['24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35+'];

export const SHOE_SIZES = ['4-5', '5-6', '6-7', '7-8', '8-9', '9-10', '10-11', '11+'];

export const BUCKETS = ['casual', 'bohemian', 'activeWear', 'vintage', 'businessCasual', 'hipHop', 'skater', 'punkRock'];

export const GENDER = ['women', 'mens', 'unisex', 'children'];

export const FILTER_IDS = ['buckets', 'merchant', 'sizes', 'gender'];

export const BRANDS = [
    'Addition Elle',
    'Adidas',
    'Aéropostale',
    "Al's Formal Wear",
    'ALDO',
    'American Apparel',
    'American Eagle',
    'Andy & Evan',
    'Anine Bing',
    'Ann Inc.',
    'Anna Sui',
    'Anthropologie',
    'Aritzia',
    'Armani',
    'ASDA',
    'ASICS',
    'Avenue',
    'Bally',
    'Banana Republic',
    'Barneys New York',
    'Bath & Body Works',
    'BCBG Max Azria',
    'Belle Bershka',
    'Bergdorf Goodman',
    'Beyond the Rack',
    'BHLDN',
    'Big Bazaar',
    'Big W',
    'Billabong',
    'Billionaire Boys Club',
    "Bloomingdale's",
    'Bonobos',
    'Bonprix',
    'BonWorth',
    'boohoo',
    "Boscov's",
    'Bottega Veneta',
    'Brayola',
    'Brighton Collectibles',
    'Brooks Brothers',
    'Brooks Sports',
    'Calvin Klein',
    'Buckle',
    'Buffalo Exchange',
    'C. Wonder',
    'Calzedonia',
    'Camp Beverly Hills',
    'Campmor',
    'Canada Goose',
    'Carhartt',
    'CAROLL',
    "Carter's",
    'Cato Corporation',
    'CELINE',
    'celio Champion',
    'Chanel',
    "Chico's",
    'Charlotte Russe',
    'Charming Charlie',
    'Christopher & Banks',
    'Citi Trends',
    "Claire's Clarks COACH",
    'Club Monaco',
    'Coldwater Creek',
    'Cole Haan',
    'Converse',
    'Columbia Sportswear',
    'Cool-jams',
    'Cortefiel',
    'Cotton On',
    'Crazy Shirts',
    "David's Bridal",
    "Davidson's",
    'Deb Shops',
    'Decathlon',
    'Destination Maternity',
    'Destination XL Group',
    "Dillard's",
    'DKNY',
    'DL1961',
    'Dolce & Gabbana',
    'Dr. Martens',
    'DressBarn',
    'Dressmann',
    'DSW',
    'Duluth Trading Company',
    'Eddie Bauer',
    'Eileen Fisher',
    'Express',
    'Famous Footwear',
    'Enfants Riches Déprimés',
    'Fanatics',
    'Fanzz',
    'Fashion Nova',
    'Fashion To Figure',
    'Fila Fjällräven',
    'Foot Locker',
    'Foschini',
    'Forever 21',
    'Fossil',
    'Frank And Oak',
    'Fred Segal',
    "Frederick's of Hollywood",
    'Free people',
    'Fruit of the Loom',
    'Fullbeauty Brands',
    'Furla',
    'Gap',
    'G-Star RAW',
    'Gant',
    'Garage',
    'Gerry Weber',
    'Gilly Hicks',
    "Glik's",
    'Gucci',
    'Guess',
    'H&M',
    'Gymboree',
    'Halls',
    'Hamilton Shirts',
    "Hamrick's",
    'Han Kjøbenhavn',
    'Hanes',
    'Harry Rosen Inc.',
    'Helly Hansen',
    'Hermès',
    'Hollister Co.',
    'Henry Singer',
    "Herberger's",
    'Hickey Freeman',
    'Holt Renfrew',
    'Hot Topic',
    "Hudson's",
    "Hudson's Bay",
    'Hugo Boss',
    'Intimissimi',
    'J. Peterman Company',
    'J. Press',
    'J.Lindeberg',
    'Jack & Jones',
    'Janie and Jack',
    'JD Sports',
    'Jessica Simpson',
    'Jil Sander',
    'Jockey Joe Fresh',
    'John Lewis Jordan',
    'Johnny Cupcakes',
    'Johnston & Murphy',
    'Jos. A. Bank',
    'JustFab',
    'Kate Spade',
    'Karen Millen',
    'Karmaloop',
    'Kmart',
    'Kenneth Cole Productions',
    'Kitson',
    "Kohl's",
    'Simons',
    'La Senza',
    'Lacoste',
    "Lands' End",
    'Levi Strauss & Co',
    'Lane Bryant',
    'Lansky Brothers',
    'Laura',
    'Le Château',
    'League Collegiate Wear',
    'Li-Ning',
    'Longchamp',
    'Louis Vuitton',
    'Life Is Good Company',
    'Limited Too',
    'Live Breathe Futbol',
    'Lucchese Boot Company',
    'LuLaRoe',
    'Lululemon',
    "Macy's",
    'Mammut',
    'Mango',
    'Marciano Stores',
    "Mark's",
    'Marks & Spencer Marni',
    'Marmot',
    'Marshalls',
    'Massimo Dutti',
    'Matalan',
    'Maui and Sons',
    'Maurices',
    'Mexx',
    'Milly',
    'Moncler',
    'Mizuno',
    'Moores',
    'Moosejaw',
    'Morsam Fashions',
    "Men's Wearhouse",
    'Naartjie',
    'Nau',
    'Neiman Marcus',
    'New Balance',
    'New York & Company',
    'Nike',
    'Nine West',
    'Nordstrom',
    'OAK+FORT',
    'Oaklandish',
    "October's Very Own",
    'Old Navy',
    'Outdoor Research',
    'PacSun',
    'Pair of Thieves',
    'Patagonia',
    'Pepe Jeans',
    'Prada',
    'Paul Stuart',
    'Pelle Pelle',
    'Penningtons',
    'PrettyLittleThing',
    'Primark',
    'Prisma',
    'Pro Wrestling Tees',
    'Pull&Bear',
    'Puma Quiksilver',
    'Raleigh Haberdasher',
    'Ralph Lauren Corporation',
    'Ralph Lauren Reebok',
    'Recreational Equipment, Inc.',
    'Red Dress Boutique',
    'REI Reliance Trends',
    'Reign',
    'Reitmans',
    'Reserved',
    'REVOLVE River Island Ross Dress for Less Roxy',
    'Roots Canada',
    'Russell Athletic',
    's.Oliver Sainsbury’s-TU Clothing SAINT LAURENT',
    'Saks Fifth Avenue',
    'Salkin & Linoff',
    'Salvatore Ferragamo Sandro',
    'Semir',
    'SHEIN Skechers Speedo',
    'SINGER22',
    'Skate shop',
    'Southern Marsh Collection',
    'Southern Tide',
    'Splash',
    'Sport Chalet',
    'Sports Authority',
    'Sports Authority, Inc.',
    'Sports Direct Steve Madden Stradivarius',
    'Stanley Korshak',
    "Stern's",
    "Strawbridge's",
    "Stroud's Mercantile",
    'Superdry Takko Target Target Australia',
    'Supreme',
    'Syms Corporation',
    'Tailored Brands',
    'Talbots',
    'Tchibo Ted Baker Tesco Tezenis',
    'Tea Collection',
    "The Children's Place",
    "The Children's Place The North Face",
    'The Hempest',
    'The Limited',
    'The May Department Stores Company',
    'The Popular',
    'The Warehouse Timberland',
    'Thyme Maternity',
    'Tillys',
    'Tip Top Tailors',
    'Title Nine',
    'TJ Maxx',
    'TK Maxx',
    "Tod's Tom Ford Tom Tailor Tommy Bahama",
    "Today's Man",
    'Tom Ford',
    'Tommy Hilfiger',
    'Topman',
    'Topshop',
    'TOPVALU COLLECTION',
    'Tori Richard',
    'Torrid',
    'Tory Burch',
    'Tory Burch Triumph Truworths UGG',
    'Tourneau',
    'Trashy Lingerie',
    'Twigs Boutique',
    'Under Armour Uniqlo',
    'United Arrows United Colors of Benetton Urban Oufitters',
    'Urban Behavior',
    'Urban Outfitters',
    'Valentino Van Heusen',
    'Vans',
    'Venus Fashion',
    'Vero Moda',
    'Versace',
    'Very',
    'Victor Clothing',
    "Victoria's Secret",
    'Vineyard Vines',
    'Von Maur',
    'Walmart',
    'Warnaco Group',
    'Weber & Heilbroner',
    'West 49',
    'White House Black Market',
    'Wilkes Bashford',
    'Woolworths',
    'Wrangler',
    'Youngor Zalando Zara',
    'ZCMI',
    'Zeeman'
];

/*
export const TOP_SIZES = [
    'XS / 0',
    'XS / 2',
    'S / 4',
    'S / 6',
    'M / 8',
    'M / 10',
    'L / 12',
    'L / 14',
    'XL / 16',
    'XL / 18',
    'XXL / 22',
    'XXL / 24'
];

export const BOTTOM_SIZES = [
    '24-25 / XXS',
    '25-26 / XS',
    '27-29 / S',
    '29-32 / M',
    '33-37 / L',
    '38-41 / XL',
    '42-46 / XXL',
    '47-52 / 3XL',
    '53-58 / 4XL'
];

export const SHOE_SIZES = [
    '4 / 212',
    '5 / 220',
    '6 / 229',
    '7 / 237',
    '8 / 246',
    '9 / 254',
    '10 / 262',
    '11 / 270'
];
*/
